version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: nginx
        awslogs-region: us-east-1
        awslogs-stream-prefix: web